namespace StarSalvager.Audio
{
    public enum SOUND
    {
        BIT_SNAP = 0,
        BIT_LVL1MERGE = 1,
        BIT_LVL2MERGE,
        BIT_LVL3MERGE,
        BIT_LVL4MERGE,
        BUMPER_BONK_SHIFT,
        BUMPER_BONK_NOSHIFT,
        BIT_DAMAGE,
        PART_DAMAGE,
        ENEMY_IMPACT,
        ASTEROID_BASH,
        ASTEROID_CRUSH,
        BIT_EXPLODE,
        PART_EXPLODE,
        ENEMY_DEATH,
        BIT_BOUNCE,
        BIT_RELEASE,
        GUNLVL1_FIRE,
        GUNLVL2_FIRE,
        GUN_CLICK,
        REPAIRER_PULSE,
        REPAIRER_FAIL,
        SHIELD_ABSORB,
        SHIELD_RECHARGE,
        BOMB_BLAST,
        BOMB_CLICK,
        FLY_MOVE,
        PARASITE_MOVE,
        BALLHEAD_MOVE,
        MOSQUITO_MOVE,
        SQUID_MOVE,
        FLY_FIRE,
        PARASITE_LATCH,
        PARASITE_SUCK,
        BALLHEAD_FIRE,
        MOSQUITO_FIRE,
        BIT_REFINED,
        BOT_ROTATE = 37,
        
        BIT_SNAP_BLUE,
        BIT_SNAP_GREEN,
        BIT_SNAP_GREY,
        BIT_SNAP_RED,
        BIT_SNAP_YELLOW,
    }
}


