using System;

namespace StarSalvager
{
    [Serializable]
    public enum FACILITY_TYPE : int
    {
        FREEZER,
        STORAGEFUEL,
        STORAGEELECTRICITY,
        STORAGEPLASMA,
        STORAGESCRAP,
        STORAGEWATER,
        WORKBENCHCHIP,
        WORKBENCHCOIL,
        WORKBENCHFUSOR,
        REFINERY,
        
        SEPARATOR,
        SMELTER,
        CENTRIFUGE,
        EVAPORATOR,
        ALTERNATOR,
        PROCESSOR,
        STORAGEPARTSCOMPONENTS,
        STARTINGFUEL,
        STARTINGELECTRICITY,
        STARTINGPLASMA,
        STARTINGSCRAP,
        STARTINGWATER,
        WORKBENCHEFFICIENCY,
        RECOVERYDRONE,
        LAYOUTSAVE,
        RADAR,
        MECHANICS,
        COOLING,
        HULLSTRENGTH,

        CONTAINERIMPROVE,
        REPAIRERIMPROVE,
        BOOSTIMPROVE,
        AMMODISCOUNT,
        KILLGEARS,
        COOLDOWNDECREASE,
        ROTATESPEEDINCREASE,
        LOOTDROPINCREASE,
        COREREPAIRSREGEN
    }
}